### ISSUE TITLE
Job progress is broken

### ISSUE THREAD

**Issue by dostu** [bee-queue/arena#102]
Job progress is always 0%. 

I believe [this](https://github.com/bee-queue/arena/commit/33f730a69f45c2887f6fcd1ad48e42250b214782#diff-9a220580a657ea11601817f0fa5303f9) commit introduced the problem.

Does anyone else face the same issue? If it's not just me, maybe we should revert that commit?

**Comment by wmhafiz** [comment]
its not just you. can confirm i was able to fix by reverting that commit. thanks!

**Comment by ttacon** [comment]
For clarification, which bull or bee-queue version are you using?

**Comment by dostu** [comment]
I'm using bull 3.4.2

**Comment by LukeStonehm** [comment]
I too am getting this issue with Bull 3.4.2.
