### ISSUE TITLE
`app.use('/jobs', arena)` + `basePath : '/jobs'` listens on "/jobs/jobs" instead of "/jobs"

### ISSUE THREAD

**Issue by Ilshidur** [bee-queue/arena#105]
As said in the title, I think the routing is incorrect when using this module with nested routes.

Example :

```javascript
const arena = Arena({
  queues: [
    {
      // ...
    }
  ],
}, {
  basePath: '/jobs',
  disableListen: true,
});

// [...]

app.use('/jobs', arena);
// Only reachable by accessing `/jobs/jobs` route
```

When accessing the dashboard on `/jobs/jobs`, the assets can't be accessed and the assets requests results in a 404 error : `/jobs/dashboard.css` (happens with the other assets).

It this an intended behavior ? If so, I didn't find any doc about this :-(
Is this a bug ? If so, [I opened a MR solving this problem](https://github.com/bee-queue/arena/pull/106) in case this is indeed a bug.

Thanks for this great lib by the way !

**Comment by hraban** [comment]
Ran into the same problem. Work around:

```ts
const app = express();
// ...

// URL Rewriting rigmarole necessary because bull-arena expects to be mounted
// on root path. I don't want to do that here because I want to encapsulate
// the bull arena, most importantly for security reasons (password and CSP).
const arena = express.Router();
arena.use((req, res, next) => { req.url = `/arena${req.url}`; next(); });
arena.use(new Arena({queues}, {basePath: '/arena', disableListen: true, ...}));
app.use('/arena', arena);
```
