### ISSUE TITLE
ReferenceError: jobTypes is not defined

### ISSUE THREAD

**Issue by milesalex** [bee-queue/arena#110]
```
(node:27) UnhandledPromiseRejectionWarning: 
Unhandled promise rejection (rejection id: 2): 
ReferenceError: jobTypes is not defined
```

When I try to click into the job types on the main page I get this error. For example when I try to see all  `complete` jobs.

Using bull. Will try to fix the error when I have some extra time.

**Comment by tylercollier** [comment]
I went back to commit eef2b1a. If you do a `git reset --hard`, don't forget to save off your `src/server/config/index.json`!

**Comment by milesalex** [comment]
@tylercollier  Ahh, actually I just fixed this bug in the PR referenced.
