### ISSUE TITLE
Custom Job id and collapse error

### ISSUE THREAD

**Issue by ezsper** [bee-queue/arena#116]
If `/` or other special character (not escaped in the `encodeIdAttr` function) are present in the job id, the job details when collapsed won't open and an error is thrown in the console by `jquery.bootstrap`.

This is a problem when using custom job ids, and in my case with those special characters on it.

To fix this you can simply replace in file [src/server/views/helpers/handlebars.js:43](https://github.com/bee-queue/arena/blob/master/src/server/views/helpers/handlebars.js#L43) the code:
`return id.replace(/:| /g, '');`
with
`return Buffer.from(id).toString('base64').replace(/=/g, '');`
or any other hash, `encodeURIComponent` doesn't work either as `%` also throws an error.

Or simply use a sequential id, really.

**Comment by ttacon** [comment]
Great debugging! PRs are always welcome 😄! We should be handling this and allowing users to use custom names.

**Comment by ashkank83** [comment]
Hi, Any plans to merge this fix please? Thanks

**Comment by ttacon** [comment]
Hi! I'm not sure what fix you mean, @ashkank83 ? This is an issue - could you link me to the PR that you're referring to? Cheers!

**Comment by ashkank83** [comment]
@ttacon Thanks for the reply. I may be (probably am) mistaken but I see three commits by gcox linked to this issue and thought this the fix for the issue. Am I wrong?

**Comment by ttacon** [comment]
Hi @ashkank83! Ah, this is GitHub's UI not being very clear. It looks like `gcox` pushed those commits up to their own branch, but unless I'm missing it, a PR hasn't been opened to this repo yet. More than happy to be pointed to the PR or to review a PR to this repo!

**Comment by skeggse** [comment]
@ttacon https://github.com/bee-queue/arena/pull/126

**Comment by ttacon** [comment]
Ah, thanks @skeggse ! I've added one comment on that PR, after that's addressed we'll merge and publish a new version.

**Comment by ttacon** [comment]
`bull-arena@2.5.2` contains this fix.
