### ISSUE TITLE
Cannot remove stuck bull job

### ISSUE THREAD

**Issue by milutin-apostol** [bee-queue/arena#124]
Cant remove stuck bull job.
When click `Remove Job` button this is the response from server:

`{error: "queue error",…}
details
:
"Error: Could not remove job c5872330-794e-495a-b188-66c785df192b↵    at /home/apostol7/Desktop/arena/arena/node_modules/bull/lib/job.js:372:13↵    at tryCatcher (/home/apostol7/Desktop/arena/arena/node_modules/bluebird/js/release/util.js:16:23)↵    at Promise._settlePromiseFromHandler (/home/apostol7/Desktop/arena/arena/node_modules/bluebird/js/release/promise.js:512:31)↵    at Promise._settlePromise (/home/apostol7/Desktop/arena/arena/node_modules/bluebird/js/release/promise.js:569:18)↵    at Promise._settlePromise0 (/home/apostol7/Desktop/arena/arena/node_modules/bluebird/js/release/promise.js:614:10)↵    at Promise._settlePromises (/home/apostol7/Desktop/arena/arena/node_modules/bluebird/js/release/promise.js:693:18)↵    at Async._drainQueue (/home/apostol7/Desktop/arena/arena/node_modules/bluebird/js/release/async.js:133:16)↵    at Async._drainQueues (/home/apostol7/Desktop/arena/arena/node_modules/bluebird/js/release/async.js:143:10)↵    at Immediate.Async.drainQueues (/home/apostol7/Desktop/arena/arena/node_modules/bluebird/js/release/async.js:17:14)↵    at runCallback (timers.js:810:20)↵    at tryOnImmediate (timers.js:768:5)↵    at processImmediate [as _immediateCallback] (timers.js:745:5)"
error
:
"queue error"`

Thank you!

**Comment by fbukevin** [comment]
I encounter this error too.

**Comment by skeggse** [comment]
Happy to help with this if you can provide repro steps!
