### ISSUE TITLE
Retry button fires a remove action

### ISSUE THREAD

**Issue by pdcp1** [bee-queue/arena#134]
When I select a failed job and click "Retry Jobs", it actually fires a "Remove" action in the same way as "Remove jobs" button.
I found this call in Chrome Dev Tool console when I clicked "Retry Jobs"

![image](https://user-images.githubusercontent.com/6564809/48783935-4f1d5b00-ecc0-11e8-8fc7-758fa7851753.png)

**Comment by bradvogel** [comment]
It's working correctly - retry a few jobs and watch the attempts count increase.

The reason it works is that "Retry" sends an HTTP PATCH request whereas "Remove" sends an HTTP POST request.
