### ISSUE TITLE
Dashboard isn't updating.

### ISSUE THREAD

**Issue by shaklinThrill** [bee-queue/arena#135]
Have Setup arena, Test Queue behaves as expected while testing through Terminal queue status gets printed, while checked on the dashboard there is no update. 

```
testQueue.process(function(job, complete){
  console.log("Inside Test Queue", job.id);
  complete();
  testQueue.count().then(function(data){
    console.log(data);
  })
})
```

```
testQueue.on('completed', function(job){
  console.log("Inside Complete", job.id)
})
```
Arena is setup at different app. 
The Config as follows:
```
  const arena = new Arena({
    queues: [{
      "name": "testQueue",
      "port": 6379,
      "host": "127.0.0.1",
      "hostId": "Test"
    }]},{
      basePath: '/',
      disableListen: true
  });
```

<img width="359" alt="screenshot 2018-11-27 at 3 41 55 am" src="https://user-images.githubusercontent.com/42565041/49045304-99d63000-f1f6-11e8-8697-272297e6deeb.png">

![image](https://user-images.githubusercontent.com/42565041/49045338-b83c2b80-f1f6-11e8-8078-cb7c5f8dc7b8.png)

Any suggestions?
Thanks

**Comment by NourSammour** [comment]
@shaklinThrill I've the same issue, did you solve it?

**Comment by c060604** [comment]
I also have the same issue. I use version `2.5.1`.

### Arena Dashboard:
![image](https://user-images.githubusercontent.com/5510945/50212024-fe7b4980-03b4-11e9-9ec8-ebbff8359561.png)

### Redis keys:
![image](https://user-images.githubusercontent.com/5510945/50212081-1bb01800-03b5-11e9-9536-f79e6c1a422b.png)

### Arena config:
![image](https://user-images.githubusercontent.com/5510945/50212130-3d110400-03b5-11e9-84d9-cfb7a740748a.png)

**Comment by ttacon** [comment]
Hi folks!

@shaklinThrill and @NourSammour are you using bee-queue or bull-queue?

@c060604 are you sure that there are jobs actively in those states when viewing in arena? The Redis commands shows that the queues are there but we need to see if there are actively jobs inside them, too.

**Comment by c060604** [comment]
@ttacon  how to check the jobs are actively or not?

### Redis jobs
![image](https://user-images.githubusercontent.com/5510945/50262157-b575d480-044a-11e9-90d2-e52bca60570c.png)

### Bee-queue code & output
![image](https://user-images.githubusercontent.com/5510945/50262184-d50cfd00-044a-11e9-9dec-658193f73e9d.png)

![image](https://user-images.githubusercontent.com/5510945/50262210-f0780800-044a-11e9-8fc4-33844261b8de.png)

**Comment by c060604** [comment]
@ttacon I see, I config a wrong queue name in the `index.json`. Thank you all the same.

**Comment by shaklinThrill** [comment]
> @shaklinThrill I've the same issue, did you solve it?

Still the same.

**Comment by shaklinThrill** [comment]
> Hi folks!
> 
> @shaklinThrill and @NourSammour are you using bee-queue or bull-queue?
> 
> @c060604 are you sure that there are jobs actively in those states when viewing in arena? The Redis commands shows that the queues are there but we need to see if there are actively jobs inside them, too.

Bull-Queue

**Comment by ttacon** [comment]
@shaklinThrill we're currently using bee-queue so we don't have any easy way to repro this and don't have a ton of spare cycles at the moment. Having said that, what does [this line](https://github.com/bee-queue/arena/blob/master/src/server/views/dashboard/queueDetails.js#L16) output for you?

**Comment by bhanuc** [comment]
Also check the prefix in the queues object.

**Comment by NourSammour** [comment]
I've solved it by using these versions, if i upgraded to last version it's not working
```
    "bull": "3.3.7",
    "bull-arena": "^2.5.1",
```

**Comment by ttacon** [comment]
@NourSammour if you upgrade to the last version of which one (or is it both)?

**Comment by NourSammour** [comment]
`"bull": "3.3.7"` is required to make `bull-arena` works

**Comment by joaomilho** [comment]
Why isn't the precise version not set as a peer dependency then? Would help.

**Comment by sashamitrovich** [comment]
Same issue here - using Bull, dashboard not updating.

**Comment by skeggse** [comment]
Hey folks! Is this still a problem? We'd like to work on getting it fixed if so, and you could help us understand the problem by posting a [reprex](https://stackoverflow.com/help/minimal-reproducible-example) - something self-contained that we can use to dig in.
