### ISSUE TITLE
Show timestamp + delay info

### ISSUE THREAD

**Issue by flaviolivolsi** [bee-queue/arena#145]
Hi,

I'm not sure if I'm missing something or it's just not implemented, but for delayed jobs I can't seem to find the time of the actual execution of the job. Example: job is sent the 19th of January at 09:00am with a delay of 5 hours, but I can't see anywhere on the dashboard that the job will be executed the same day at 02:00pm.

I would be happy to shoot a PR for this, please just confirm that it's missing.

Best,
Flavio

**Comment by JensVanhooydonck** [comment]
I was thinking the same thing. Can't find it either.

**Comment by flaviolivolsi** [comment]
@JensVanhooydonck ok, so I have at lease you confirming I'm not blind :) I'll probably submit a PR whenever I can.

**Comment by flaviolivolsi** [comment]
@JensVanhooydonck ok, so I have at lease you confirming I'm not blind :) I'll probably submit a PR whenever I can.

**Comment by JensVanhooydonck** [comment]
> @JensVanhooydonck ok, so I have at lease you confirming I'm not blind :) I'll probably submit a PR whenever I can.

I already submitted a PR. you could check this if you like? I only tested it with Bull, i don't know if u use bee-queue ?

**Comment by roggervalf** [comment]
@flaviolivolsi could you please try last version, PR to address this was merged.

**Comment by bradvogel** [comment]
https://github.com/bee-queue/arena/pull/350

**Comment by bradvogel** [comment]
Fixed in new release 3.17.0
