### ISSUE TITLE
unable to connect to redis in docker

### ISSUE THREAD

**Issue by maikelmclauflin** [bee-queue/arena#159]
https://stackoverflow.com/questions/55051957/unable-to-connect-queue-to-docker-container

i'm probably just doing it wrong, but the docs are a bit sketch on this, and i have tried everything that i can think of

**Comment by maikelmclauflin** [comment]
may just need an update to docker hub since pulled version is different from locally built

**Comment by skeggse** [comment]
Closing in favor of #171 - please re-open if there's still an issue. Happy to field a PR to improve docs.
