### ISSUE TITLE
Bull readme examples uses spaces in queue names, but arena do not work with spaces 

### ISSUE THREAD

**Issue by ArnaudValensi** [bee-queue/arena#165]
I've just setup Bull/Arena combo and I scratched my head to understand why it was not working. If you follow the Bull readme examples, it will not work with Arena since they use spaces in queue names. It would be nice to either make arena work with space or add a warning in the readme.

**Comment by combizs** [comment]
What didn't work specifically?  I just created a Bull queue instance with a space in its queue name and was able to link to it with arena with a spaces in the name + hostId.

![image](https://user-images.githubusercontent.com/749396/66378073-97d91380-e967-11e9-8c9b-5ed8663cbba0.png)
