### ISSUE TITLE
Redis configuration sample index.js

### ISSUE THREAD

**Issue by sashamitrovich** [bee-queue/arena#167]
I'm too stupid, can you please provide a Redis-configured sample index.json? Thanks.

**Comment by tjmabey** [comment]
this is what I have working for me right now.

```
{  
    "queues": [
        {
            "name": "my-queue",
            "hostId": "whatever you want",
            "url": "redis://[user]:password]@[host]:[port]"
        }
    ] 
}
```
note that `name` needs to match the name you pass in when you initiate your queue.

also the full readme example for the `url` is 
`"[redis:]//[[user][:password@]][host][:port][/db-number][?db=db-number[&password=bar[&option=value]]]"`

I didn't need the db or password or option stuff but you may depending on your redis configuration.

**Comment by sibelius** [comment]
I think we can close this

**Comment by skeggse** [comment]
That seems reasonable.

**Comment by atwright147** [comment]
@tjmabey I could not get this to work -- thank you for the hint

The docs for this config are pretty terrible
