### ISSUE TITLE
Docker image on docker hub really outdated

### ISSUE THREAD

**Issue by phryneas** [bee-queue/arena#171]
Hi there!

The docker image on https://hub.docker.com/r/mixmaxhq/arena/tags still points to v2.0.2, which is missing a bug fix and crashes for me on every finished bull job.

Could you please push an updated versions?

Thanks a lot :)

**Comment by focux** [comment]
I was about to open an issue about this, cc: @ttacon

**Comment by skeggse** [comment]
I've got the image built - still working on getting it uploaded.

**Comment by skeggse** [comment]
Uploaded through 2.6.3. If you have thoughts on automating this process, please share - I can't guarantee that we'll stay up-to-date otherwise.

**Comment by phryneas** [comment]
@skeggse you can just configure dockerhub to auto-build from a branch or tag on github:
https://docs.docker.com/docker-hub/builds/

**Comment by phryneas** [comment]
Oh, and thank you! :)
