### ISSUE TITLE
mixmaxhq/arena docker image `latest` tag out-to-date

### ISSUE THREAD

**Issue by Kmaschta** [bee-queue/arena#174]
Hi here!

I saw the issue here #171 but the the latest tag has not been updated since two years.

![image](https://user-images.githubusercontent.com/1819833/58890028-27389680-86ea-11e9-9634-b9ac027f2dca.png)

In fact, when you pull the docker image with a version tag, it works just well, but when you set no tag docker get the `latest` tag and this one is clearly outdated.

```bash
docker pull mixmaxhq/arena:v2.6.3 # This one get the latest version
docker pull mixmaxhq/arena # This one is outdated
```

When publishing a new version, the publisher should update the `latest` tag too :

```bash
docker build -t mixmaxhq/arena .
docker tag deli mixmaxhq/arena:VERSION
docker tag deli mixmaxhq/arena:latest
docker push mixmaxhq/arena:VERSION
docker push mixmaxhq/arena:latest
```

In the meantime, the workaround is to always tag your docker image when pulling it.

Hope that I helped!

**Comment by skeggse** [comment]
Done. Feel free to open a PR automating the process or adding documentation somewhere - we don't actually use the docker-hosted arena, and didn't add the dockerfile originally so while we'll do our best, I can't promise it'll stay up to date.
