### ISSUE TITLE
Cant get to the queue page with bull-arena

### ISSUE THREAD

**Issue by gete76** [bee-queue/arena#182]
Hi there,
I've setup bull-arena according to the docs but when I click on the queue name for queue details on the homepage at /arena, the request just hangs and then fails. I see it's hanging on the Queue.getJobCounts call.   Here's what the basic app setup looks like. Any help would be appreciated. Thanks!

       const Arena = require('bull-arena')
       const express = require('express')
       const app = express()
       const { config } = require('./config/config')
   
       const bodyParser = require('body-parser')
       const cors = require('cors')
       const routes = require('./src/routes')
       const arena = Arena({
       queues:[
           {
            "name": config.queue_name,
            "hostId": "ImageMigrate",
            "redis": {"port":6709, "host":"localhost"}
            }
        ]
        },{
             basePath: '/',
             disableListen: false
        })

       app.use(cors())
       app.use(bodyParser.urlencoded({ extended: false }))
       app.use(bodyParser.json())
       app.use('/arena', arena)

      routes(app)

**Comment by darbio** [comment]
Not sure if this is the problem, however you haven't specified the `password` property in `arena.queues[0].redis.password`.

I was having the same problem when this wasn't set - maybe try setting it to undefined? Alternatively, for localhost, you could try not setting `redis` at all it and it will default to `redis://:@127.0.0.1` (I don't use localhost so haven't tested this).

**Comment by combizs** [comment]
@darbio, password may not necessarily need to be provided; default redis config has no password.

**Comment by combizs** [comment]
@gete76, check your local redis configuration to see if:
- it requires a password
  - default setup does not have password
- the redis port number is correct
  - default port is 6376
- redis instance is running locally;
  - go to your redis directory; `redis-x.x.x`
  - run `src/redis-server` in your terminal

**Comment by darbio** [comment]
@combizs yeah I thought so too, but I had a similar issue when I didn’t set the password property. From memory, setting it to undefined solved the issue for me.

**Comment by brianschardt** [comment]
So what was the solution for this?

**Comment by combizs** [comment]
@brianschardt, based on the latest version, it worked for me.  Just check the following: 
https://github.com/bee-queue/arena/issues/182#issuecomment-539389709

**Comment by ttacon** [comment]
Closing as @combizs has supplied a solution with debugging steps. Please let me know if you'd like this to be re-opened!

**Comment by sudhagar10** [comment]
I am facing this issue. 

It works fine locally. But once I took things to staging, viewing Queue page always times out.


Below is the configuration code.
queues: [
      {
        // Name of the bull queue, this name must match up exactly with what you've defined in bull.
        name: config.worker.queues.default.name,

        // Hostname or queue prefix, you can put whatever you want.
        hostId: 'Q',

        // Redis auth.
        redis: {
          url: config.redis.url,
        },
      },
    ],

**Comment by george-norris-salesforce** [comment]
Same issue, I can get the index page working. When I click on a link, it never resolves.
```
const arenaConfig = Arena({
  queues: [{
    // Name of the bull queue, this name must match up exactly with what you've defined in bull.
    name: 'ImportWork',
    // Hostname or queue prefix, you can put whatever you want.
    hostId: 'Import Jobs',
    // Redis auth.
    redis: {
      port: '6379',
      host: process.env.REDIS_URL
    },
  },
  ],
},
{
  // Make the arena dashboard become available at {my-site.com}/arena.
  basePath: '/admin',

  // Let express handle the listening.
  disableListen: true
});

route.use('/', arenaConfig);
```

**Comment by rushilsrivastava** [comment]
This issue definitely still exists, facing the exact same problem as the people above

**Comment by yan-michael** [comment]
I am also having this problem.

**Comment by rrdlpl** [comment]
me too

**Comment by Rocamonde** [comment]
I happen to have this problem too. This is my configuration:

```
const arenaConfig = Arena(
  {
    queues: [
      {
        name: 'newsQueue',
        hostId: 'newsQueue',
        redis: {
          url: REDIS_ADDRESS,
        },
      },
    ],
  },
  {
    basePath: '/arena',
    disableListen: true,
  }
);

app.use('/', arenaConfig);
```

The `/arena` route loads, but when I click on any of the routes, the request is never resolved. I tried using `url` and `path` as the name of the Redis address parameter. My variable is correct as is the one I use to load Bull in another part of the App, and Bull is working perfectly.

Any thoughts of what I might be doing wrong, or is this a bug in the code? Makes the package pretty useless, if so.

**Comment by skeggse** [comment]
This sounds like it's related to these: #123 #162 #164, given that all the configs we've seen are using a specific subpath. If anyone has an example that doesn't use a `basePath`, please feel free to re-open!

**Comment by edengabay** [comment]
Any chance of solving it?
It is easily reproduced when using docker-compose.
