### ISSUE TITLE
Ability to promote jobs from delayed

### ISSUE THREAD

**Issue by bogdan** [bee-queue/arena#203]
Please add "Promote" button for delayed jobs:

![image](https://user-images.githubusercontent.com/122436/74362653-b9dd1980-4dd1-11ea-8f87-4065bc81c7f0.png)

**Comment by tevaum** [comment]
I'm thinking about implementing this, but I'm not sure how to do this for bee queues. Any clue?

**Comment by bogdan** [comment]
No, idea, however I think if the feature is only available for bull, let it be only for bull.

**Comment by tevaum** [comment]
Yeah. Looks like bee doesn't support promoting jobs. There's also a PR for this: https://github.com/bee-queue/arena/pull/177#issuecomment-622124142

If the author of that PR doesn't answer I'll try to solve the issues so that it can be merged.

**Comment by roggervalf** [comment]
@bogdan please try the last released version, both buttons were added

**Comment by roggervalf** [comment]
@bradvogel I think this issue could be closed
