### ISSUE TITLE
Ability to add raw json jobs

### ISSUE THREAD

**Issue by hraban** [bee-queue/arena#208]
Please could we also add a feature to just enter raw HTML? The current editor is very limiting: no copy paste, unintuitive icons without labels, unintuitive interface, many clicks to create simple jobs, etc...

No doubt it's useful in a streamlined workflow, but if you just want to add a quick job, this interface can be confusing and time consuming.

A little toggle to go from:

![current](https://user-images.githubusercontent.com/137852/56585168-34377580-65d5-11e9-8b61-4dd57aa56056.png)

to:

![desired](https://user-images.githubusercontent.com/137852/56585275-6ba62200-65d5-11e9-98f5-3386ea49172b.png)

would do wonders! :)

thanks

---

this issue was copied verbatim from #53; I didn't check if it's still relevant. If this is now already a feature please let me know / feel free to just close if you're an admin.

**Comment by skeggse** [comment]
Landed in v3.1.0.
