### ISSUE TITLE
Arena is not updating

### ISSUE THREAD

**Issue by robertour** [bee-queue/arena#216]
Basically I don't see the numbers moving on the GUI, although when I started the first time a few numbers were displayed, they are frozen and no longer updates:

![image](https://user-images.githubusercontent.com/1033512/80572317-5d67be80-89fe-11ea-95c5-ec227be594f1.png)

Here is my Bee Queue configuration:
```
const Queue = require('bee-queue');
const Page = require('../Page');
var log = require('./log');

class SaveQueue {
  constructor() {
    this.queue = new Queue('saves', {
      prefix: 'bq',
      stallInterval: 5000,
      nearTermWindow: 1200000,
      delayedDebounce: 1000,
      redis: {
        host: '127.0.0.1',
        port: 6379,
        db: 0,
        options: {}
      },
      isWorker: true,
      getEvents: true,
      sendEvents: true,
      storeJobs: true,
      ensureScripts: true,
      activateDelayedJobs: false,
      //do not keep jobs in memory!
      removeOnSuccess: true,
      removeOnFailure: true,
      redisScanCount: 100
    });
    let page = new Page();

    this.queue.process(async (job) => {
        let res = await page.create(job.data)
        return res;
    });

    this.queue.on('error', (err) => {
      log.error(err);
    });

    this.queue.on('failed', (job, err) => {
      log.error(err);
    });

    this.queue.on('succeeded', (job, result) => {
      log.msg(`Finished job: ${job.id}`);
    });

  }

  add_page(page){
    let job = this.queue.createJob(page);
    job
      .timeout(120000)
      .retries(0)
      .save()
      .then((job) => {
        console.log(`Enqueued job: ${job.id} `);
      })
  }
}

module.exports = new SaveQueue();
```

And my index.json configuration:
```
{
  "queues": [
    {
      "host": "127.0.0.1",
      "port": 6379,
      "name": "saves",
      "hostId": "my host",
      "type": "bee",
      "prefix": "bq",
      "db": 0

    }
  ]
}
```

Is it maybe because I don't keep the jobs in memory (see `removeOnSuccess`, and `removeOnFailure`)? In principle, I just want to see the counters. What is the `db` parameter?

**Comment by skeggse** [comment]
I can't make much out of your example - it looks reasonable to me, but it's not complete without the rest of the files. Can you post a [reprex](https://stackoverflow.com/help/minimal-reproducible-example)?

> Is it maybe because I don't keep the jobs in memory (see `removeOnSuccess`, and `removeOnFailure`)?

That's entirely likely, yeah. To be clear, we don't live-update the dashboard - it doesn't change when you reload?

> What is the `db` parameter?

See [SELECT](https://redis.io/commands/select).

> In principle, I just want to see the counters.

`arena` just reports the size of various data structures used by bee-queue or bull. To my knowledge, neither library keeps a historical record of counters, so you'd need to add additional functionality to track that. Does that address your concern?

**Comment by robertour** [comment]
Thanks, I am monitoring this differently now, `removeOnSuccess` and `removeOnFailure` seems to be the source of my problem, and I do need them there.

**Comment by juanmanavarro** [comment]
> Thanks, I am monitoring this differently now, `removeOnSuccess` and `removeOnFailure` seems to be the source of my problem, and I do need them there.

Please, add this to docs. Thanks
