### ISSUE TITLE
Improve performance for bull queue when used as remote monitor

### ISSUE THREAD

**Issue by meotimdihia** [bee-queue/arena#220]
I tried to monitor remote Redis-server
I can't load the page if the queue number is more than 1000. I checked and saw `arena` was stopped in these lines:

https://github.com/bee-queue/arena/blob/master/src/server/views/dashboard/queueJobsByState.js#L106-L110
https://github.com/bee-queue/arena/blob/master/src/server/views/dashboard/queueJobsByState.js#L99-L103

And everything is fine if I use https://github.com/mixmaxhq/arena/blob/master/src/server/views/dashboard/queueJobsByState.js
He removed these lines and it works perfectly.

**Comment by skeggse** [comment]
Feel free to submit a pull request to fix this!

**Comment by roggervalf** [comment]
@meotimdihia could you please try the last version, there is one pr that was merged referencing this issue

**Comment by meotimdihia** [comment]
Sorry, currently I don't use Bee or Bull queue for my project.

**Comment by roggervalf** [comment]
> Sorry, currently I don't use Bee or Bull queue for my project.

No worries, could this issue be closed?

**Comment by meotimdihia** [comment]
Yes, I close this issue. 😀
