### ISSUE TITLE
Unexpected behavior with manual retries from Delayed Queue

### ISSUE THREAD

**Issue by xelzi** [bee-queue/arena#222]
I am having issues when I try to manually retry a job in the Delayed Queue using `Trigger`. 

Instead of this job retrying -- a new job is being created. This new job also nests the original parameters in a way that guarantees the retry will fail 😅 

## The Original Job -- has an id of 35:
![Screen Shot 2020-05-21 at 5 27 26 PM](https://user-images.githubusercontent.com/14365312/82608384-92dc7380-9b88-11ea-8cd2-a32730b6978c.png)

## The New Job -- includes the original job id of 35 and nests the parameters ❓ ❓ ❓ :
![Screen Shot 2020-05-21 at 5 28 41 PM](https://user-images.githubusercontent.com/14365312/82608418-a7207080-9b88-11ea-9ffd-3a1ad070b88a.png)

## Expected Behavior
1) No duplicated Job is created
2) The retry count on the original job is iterated on

**Comment by theoephraim** [comment]
I noticed this nested parameter issue happening as well with re-triggering a successful job.
I would have expected a new job to be created with the same payload, not with all the job metadata nested under data.

**Comment by roychri** [comment]
I made a PR to fix this issue.

**Comment by softmantk** [comment]
This is really critical bug! Can someone merge this ?

**Comment by skeggse** [comment]
Released in v2.8.2.
