### ISSUE TITLE
Remove dependency on `handlebars-helpers`

### ISSUE THREAD

**Issue by connorskees** [bee-queue/arena#226]
Hello,

I am wondering if it would be possible for `arena` to drop its dependency on `handlebars-helpers`. This single dependency is responsible for *177* transitive dependencies -- you can see a particularly striking visualization of this at https://npm.anvaka.com/#!/view/2d/handlebars-helpers. 

As far as I can tell, this project does not non-trivially rely on `handlebars-helpers` for any functionality. I was able to replace presumably all uses of this library in only 6 lines,

```javascript
handlebars.registerHelper("encodeURI", encodeURIComponent);
handlebars.registerHelper("capitalize", (s) => s.charAt(0).toUpperCase() + s.slice(1));
handlebars.registerHelper("add", (a, b) => Number(a) + Number(b));
handlebars.registerHelper("subtract", (a, b) => Number(a) - Number(b));
handlebars.registerHelper("length", (a) => a.length);
handlebars.registerHelper("moment", (date, format) => moment(date).format(format));
```

**Comment by roychri** [comment]
Somehow I completely missed the pull #227 !
I'll do what was done in #227 + what was asked and resubmit!
