### ISSUE TITLE
v3.0.0 how to provide queue constructor

### ISSUE THREAD

**Issue by apmcodes** [bee-queue/arena#233]
Not able to find any doc on how to add queue constructor. Can someone provide an example?

**Comment by skeggse** [comment]
That's [this part](https://github.com/bee-queue/arena#usage) of the README:

```js
const Arena = require('bull-arena');

// Mandatory import of queue library.
const Bee = require('bee-queue');

Arena({
  // All queue libraries used must be explicitly imported and included.
  Bee,
```

It sounds like the readme isn't clear about this - how might we improve it to help with adoption and comprehension?

**Comment by dhritzkiv** [comment]
Keeping the [DefinitelyTyped TS definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/bull-arena/index.d.ts) up to date would also help with adoption

**Comment by skeggse** [comment]
Today I learned there are external TS definitions for this project.

**Comment by skeggse** [comment]
What's the current standard around shipping an `index.d.ts` file with the project itself vs putting it in `DefinitelyTyped`? I could add it here, but then maybe I'd need to pull in `@types/express` and `@types/redis` - I assume I'd need to ship those - and maybe also pull in `bee-queue` and `bull` for those typescript users who want the types to work. Maybe that's a reason to use `DefinitelyTyped`?

**Comment by dhritzkiv** [comment]
Generally, if the underlying project is Typescript, and types are automatically generated, then you include it with the repo + release.

But if it's adding types after the fact, DefinitelyTyped is probably the way to go, especially since additions to the DefinitelyTyped repo are relatively quickly reviewed + published, so if the original repo becomes unmaintained, types can still be fixed up + published. It also allows those who don't need the definitions to skip them + their dependencies.

**Comment by chaffeqa** [comment]
Yeah honestly this is blocking us from adopting v3... we heavily use TS and its gonna break a ton changing to the v3 version

**Comment by skeggse** [comment]
Alright well I really don't know anything about typescript but here's my attempt to update: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46626

**Comment by gtpan77** [comment]
This issue is fixed. @skeggse close this issue.
[DefinitelyTyped/pull/48242](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48242)

**Comment by skeggse** [comment]
Thank you!
