### ISSUE TITLE
Named jobs are triggered with __default__ name

### ISSUE THREAD

**Issue by dhritzkiv** [bee-queue/arena#234]
v2.8.2 (I haven't upgraded to 3.0+, yet) broke how "triggering" named jobs were saved: the `name` is ignore and the `__default__` one is used.

v2.8.1 and below worked fine.

**Comment by skeggse** [comment]
> broke how "triggering" named jobs were saved

I'm not sure I follow - what do you mean by this?

I don't see any functional changes that would have impacted this in the 2.8.2 release.

**Comment by dhritzkiv** [comment]
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/1349865/89471938-54009780-d74d-11ea-9b2c-e059f3117a75.png">

In the delayed jobs queue, pressing "Trigger" saves a new job, but strips off the name (I redacted it - Sorry!). I imagine this also happens in Failed Jobs.

Could it have been introduced in #223? Where before passing the `job` (and not `job.data`) saved the entire job as-is, including its name?

In any case, the `name` of a job isn't being included during trigger/retry.

**Comment by skeggse** [comment]
Thanks for the additional explanation - I'm not very familiar with bull or how arena supports it (who put me in charge lol)

I think this is probably related to needing to pass in the `name` to `Queues.set` as the third parameter.

**Comment by dhritzkiv** [comment]
(Btw - I added some screenshots and the JSON of the job to my comment above for each version.)

No worries! I was able to rollback to the previous version just fine.

And yes, it sounds like that's what'is missing from the code.
