### ISSUE TITLE
Could not add job using  arena dashboard - ERR_ABORTED 404 bootstrap library

### ISSUE THREAD

**Issue by gtpan77** [bee-queue/arena#274]
Using bull queue here. I think this is not related to queue type, should be some frontend issue.
Getting this error on arena dashboard -
testQueue:150 `GET https://cdn.jsdelivr.net/g/jquery@3.5.1,bootstrap@3.3.7 404`
dashboard.js:1 `Uncaught ReferenceError: $ is not defined`

<img width="1279" alt="Screenshot 2020-11-02 at 1 58 21 PM" src="https://user-images.githubusercontent.com/16515783/97846084-7f2a6100-1d13-11eb-92e2-7566e4adf0a7.png">

**Comment by skeggse** [comment]
What version of arena are you running? I believe this should be fixed in 3.3.3.

**Comment by gtpan77** [comment]
I was using 3.0.1. Yes, this is fixed already. Closing this issue.
