### ISSUE TITLE
Possibly issue with not loading jquery

### ISSUE THREAD

**Issue by rootux** [bee-queue/arena#288]
When running locally I see the UI but almost no button is clickable.

The console shows this error:
```bash
The resource from “https://cdn.jsdelivr.net/g/jquery@3.5.1,bootstrap@3.3.7” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).
2 delayed
Uncaught ReferenceError: $ is not defined
    <anonymous> http://localhost:5000/bull/dashboard.js:1
dashboard.js:1:1
```

**Comment by rootux** [comment]
It seems like when I try to open the file directly on jsdelivr it doesn't seem to exists - 
[https://cdn.jsdelivr.net/g/jquery@3.5.1,bootstrap@3.3.7](https://cdn.jsdelivr.net/g/jquery@3.5.1,bootstrap@3.3.7)

**Comment by rootux** [comment]
I do see that this works "https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" - could it be that something changed on jsdelivr?

**Comment by rootux** [comment]
I was able to fix manually it by setting `useCdn` to `false`

**Comment by jimaek** [comment]
/g/ is the legacy format that supports only old versions. It can't pull anything from npm.

This is the new format that works with npm https://cdn.jsdelivr.net/combine/npm/jquery@3.5.1,npm/bootstrap@3.3.7/dist/js/bootstrap.min.js

**Comment by rootux** [comment]
Good catch.
So probably this should be fixed to the new format

**Comment by skeggse** [comment]
Would you please confirm the version of arena you're running? I believe this isn't a problem on up-to-date arena.

**Comment by rootux** [comment]
I'm using the latest version. I believe it's 3.4.0

**Comment by skeggse** [comment]
I don't see how that's possible:
```sh
$ curl -s https://registry.npmjs.org/bull-arena/-/bull-arena-3.4.0.tgz | zgrep --binary-files=text jsdelivr
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css">
    <script type="text/javascript" src="//cdn.jsdelivr.net/combine/npm/jquery@3.5.1,npm/bootstrap@3.4.1/dist/js/bootstrap.min.js"></script>
```

**Comment by bradvogel** [comment]
Note that there's little value in using jsdelivr (vs hosting and serving these libraries) now that Chrome no longer uses a shared cache https://developers.google.com/web/updates/2020/10/http-cache-partitioning

**Comment by skeggse** [comment]
Oh dang. That's a big change. I get the rationale, but wow.

I haven't seen any evidence that this particular issue is valid, however - I believe this was fixed in a prior release.
