### ISSUE TITLE
When running as a node module, arena cannot be nested within a router

### ISSUE THREAD

**Issue by jrobson153** [bee-queue/arena#29]
I'm running arena as a node module alongside the rest of my app. For this use case it would be great to be able to nest it within a router so that the dashboard could be accessed at `someapp.com/arena/dashboard` for instance, like this:

```js
const arenaRouter = arena({ queues: getArenaConfig() }, true)
router.use('/arena', arenaRouter)
```

This is not currently possible, because all href links within the dashboard (and assets) are referenced directly at the root, i.e. `<a href="/dashboard/..."></a>`

**Comment by randallm** [comment]
Added in v2.0.1.

**Comment by sparebytes** [comment]
There another issue if arenaRouter is nested inside another router. EG: ```
const app = express();

const authenticatedRouter = express.Router();
app.use('/authenticated', authenticatedRouter);
// ...

const arenaRouter = arena({ ... }, { basePath: '/authenticated/arena', disableListen: true });
authenticatedRouter.use('/arena', arenaRouter);
```

In this example, the HTML anchors are correct `/authenticated/arena/...` but the server listens on `/authenticated/arena/authenticated/arena/...`. The only way to reconcile this is to use the arenaRouter from the app.
