### ISSUE TITLE
BullMQ example not working

### ISSUE THREAD

**Issue by HalfdanJ** [bee-queue/arena#293]
I'm trying to follow the new example from https://github.com/bee-queue/arena/pull/273 without luck in typescript. 

I have bull-arena `3.6.0` and bullmq `1.11.0` and @types/bull-arena `3.0.2`

When using the code from the readme, I get the following error: 

`TypeError: as of 3.0.0, bull-arena requires that the queue constructors be provided to Arena` 

With the following code: 

```
import Arena from 'bull-arena';
import { Queue } from 'bullmq';

const arenaConfig = Arena(
  {
    BullMQ: Queue,

    queues: [
      {
      <...>
      }
    ]
  },
  {
    // Make the arena dashboard become available at {my-site.com}/arena.
    basePath: '/',

    // Let express handle the listening.
    disableListen: true
  }
);
```

**Comment by HalfdanJ** [comment]
Ah i'm realizing now that I need to add `type: 'bullmq'` to the queue. Should that be added to the example?

**Comment by skeggse** [comment]
Yep, that seems likely to be the problem!

**Comment by skeggse** [comment]
cc @gtpan77

**Comment by gtpan77** [comment]
Thanks @skeggse for updating docs.
