### ISSUE TITLE
Action on bumping jsoneditor because of open XSS-vunerability

### ISSUE THREAD

**Issue by didrikg** [bee-queue/arena#309]
Hey,

Saw this open PR for bumping jsoneditor https://github.com/bee-queue/arena/pull/307

I just wanted to ask if there is any planned action on this as the current version has an open XSS-vunerability in it (see https://github.com/josdejong/jsoneditor/issues/1029).

Thank you!

**Comment by roggervalf** [comment]
hey @didrikg, #334 was merged, so I think we are good to close this issue
