### ISSUE TITLE
Completed count not getting incremented when a job is done

### ISSUE THREAD

**Issue by prcongithub** [bee-queue/arena#35]
bull: "3.0.0-rc.4"
 bull-arena: "2.0.3"

Whenever a job is added, I can see the active count for the queue getting incremented. However, when the job is completed, the active count goes down by 1 but the completed count remains 0.

**Comment by bradvogel** [comment]
If you inspect redis directly by looking at the `bull:<queueName>:completed` key, do you see jobs in there?

**Comment by prcongithub** [comment]
I think this was a temporary glitch on my local machine. Things seem to be working fine now. Will take a look at redis key as well. 
Thanks!
