### ISSUE TITLE
Job count not reflected on 3.0.0-rc.4

### ISSUE THREAD

**Issue by karthikiyengar** [bee-queue/arena#37]
The dashboard does not seem to reflect the actual statuses. Find image below

![screen shot 2017-08-05 at 7 33 39 pm](https://user-images.githubusercontent.com/8260207/28996017-2ec53c0c-7a15-11e7-9403-37eff4c951b7.png)

Here are the keys from the CLI

```
127.0.0.1:6379> keys *
1) "bull:deactivate user:2"
2) "bull:deactivate user:failed"
3) "bull:deactivate user:1"
4) "bull:deactivate user:id"
127.0.0.1:6379>
```

Here's my index.json
```
{
  "__example_queues": [
    {
      "name": "my_queue",
      "port": 6381,
      "host": "127.0.0.1",
      "hostId": "AWS Server 2"
    }
  ],
  "queues": [{
    "name": "aws-queue",
    "port": 6379,
    "host": "X.X.X.X",
    "hostId": "AWS Queue",
    "password": "XXX"
  }]
}
```

I'm using the docker image, if that is helpful.

**Comment by bradvogel** [comment]
Can you print the contents of list `bull:deactivate user:failed` in redis? I think it's SMEMBERS. Does it have jobs?

**Comment by karthikiyengar** [comment]
Here you go. FYI - Redis 3.0.2 wouldn't work to, so I upgraded Redis to 4.0.1, and I'm still facing the same issue.

```
127.0.0.1:6379> zrange "bull:deactivate user:failed" 0 -1
1) "1"
2) "2"
127.0.0.1:6379>
```

**Comment by karthikiyengar** [comment]
@bradvogel - Anyway I can speed this up or help out?

**Comment by karthikiyengar** [comment]
@bradvogel - Apologies for taking up your time - my configuration was off. I was not clear on using the "name" property. Digging around in the code helped clear things up. I'm closing this.

**Comment by etiennea** [comment]
Can you clarify? I have the same issue

**Comment by karthikiyengar** [comment]
@etiennea - If you look at my config, I've set the queue name as "aws-queue" in the config, wheras my queue is called as "deactivate user".
```
const deactivate = new Queue('deactivate user', { redis: config.REDIS_CONFIG });
```
The name of the queue in the config and the name of the queue you've declared must be the same :-)
