### ISSUE TITLE
[Security] Critical security issue in "handlebars" dependency

### ISSUE THREAD

**Issue by MiroslavF** [bee-queue/arena#390]
Hello.
Critical security issue was detected in one of your dependencies. Specifically in package `handlebars`. Can you please update the package?

This is the issue: https://www.npmjs.com/advisories/1670

Thanks in advance.

**Comment by roggervalf** [comment]
Hi @MiroslavF, you can try the last version, where this issue should be addressed

**Comment by roggervalf** [comment]
@MiroslavF could this issue be closed?
