### ISSUE TITLE
[SECURITY] Critical security vulnerability in express-handlebars dependency

### ISSUE THREAD

**Issue by MiroslavF** [bee-queue/arena#412]
Hi.

Recently I added issue about critical security vulnerability in handlebars dependency. This is the issue: https://github.com/bee-queue/arena/issues/390

Same vulnerability is found in another one of your dependencies: express-handlebars. Can you please update this package too?

Thanks.

**Comment by roggervalf** [comment]
@MiroslavF maybe this is what you are looking for https://github.com/bee-queue/arena/pull/379

**Comment by MiroslavF** [comment]
Oh yea that's it :) Thanks
