### ISSUE TITLE
Crashes when jobs are being processed

### ISSUE THREAD

**Issue by Slaventsiy** [bee-queue/arena#43]
Running Arena 2.1.1 in docker. Arena crashes when opened in browser and application is processing jobs. Application itself runs smoothly (uses bull v3.0.0-rc7). Here's the log:

> /opt/arena/node_modules/bull/lib/job.js:434
>   var job = new Job(queue, json.name || Job.DEFAULT_JOB_NAME, json.data, json.opts);
>   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^
> 
> TypeError: Cannot read property 'name' of undefined
>     at Function.Job.fromJSON (/opt/arena/node_modules/bull/lib/job.js:434:32)
>     at Redis.<anonymous> (/opt/arena/node_modules/bull/lib/queue.js:309:23)
>     at emitThree (events.js:135:13)
>     at Redis.emit (events.js:216:7)
>     at Redis.exports.returnReply (/opt/arena/node_modules/ioredis/lib/redis/parser.js:116:14)
>     at JavascriptRedisParser.returnReply (/opt/arena/node_modules/ioredis/lib/redis/parser.js:27:13)
>     at JavascriptRedisParser.execute (/opt/arena/node_modules/redis-parser/lib/parser.js:574:12)
>     at Socket.<anonymous> (/opt/arena/node_modules/ioredis/lib/redis/event_handler.js:107:22)
>     at emitOne (events.js:115:13)
>     at Socket.emit (events.js:210:7)
>     at addChunk (_stream_readable.js:252:12)
>     at readableAddChunk (_stream_readable.js:239:11)
>     at Socket.Readable.push (_stream_readable.js:197:10)
>     at TCP.onread (net.js:588:20)

**Comment by Slaventsiy** [comment]
Seems to only happen with repeatable jobs.

**Comment by yulianovdey** [comment]
+1. Perhaps just needs an upgrade of bull?

**Comment by bradvogel** [comment]
Yes might be. Try upgrading Bull first. If that doesn't work, then there's probably a bug with repeatable Bull jobs. I don't think we ever tested that (we use Bee Queue btw).

PRs welcome!

**Comment by IvanLinos** [comment]
Hi,
I can confirm this is still an issue even after upgrading bull to 3.3.10.
It is almost impossible to load a queue page properly if there are being processing multiple jobs at the same time (ie. concurrency 40+).

Any clue where to start looking at a fix?

**Comment by milesalex** [comment]
Getting the same error!

**Comment by Duskfall** [comment]
Same here
![image](https://user-images.githubusercontent.com/2528125/43026718-a25a9f86-8c7f-11e8-9c83-b499e71718dd.png)

**Comment by milesalex** [comment]
@Duskfall What version of arena are you using? I was using the docker image provided and then i built by own and the bug went away, but now I have other errors 🙃

**Comment by Duskfall** [comment]
@milesalex The one provided in the image, I haven't changed it to be honest :P

**Comment by ttacon** [comment]
Is everyone experiencing this using bull? @mrname which version of bull and arena are you using?
