### ISSUE TITLE
Can you help me with setup

### ISSUE THREAD

**Issue by MichalZak** [bee-queue/arena#50]
Not sure if I'm reading the instructions properly, need clarification:

Here is what I have so far:

//bull setup
var test= new Queue('test');

//arena setup
const arena = Arena({
    "name": "test",
    "port": 6381,
    "host": "127.0.0.1",
    "hostId": "Server Name"
  });
app.use('/arena', arena);

Right now no ques are showing up, its empty.  What am I doing wrong?

**Comment by krazyjakee** [comment]
Try this:

```
//bull setup
var test = new Queue('test');

//arena setup
const arena = Arena({
  queues: [{
    "name": "test",
    "port": 6381,
    "host": "127.0.0.1",
    "hostId": "Server Name"
  }]
);
app.use('/arena', arena);
```

If that doesn't work, you're going to have to manually check to see if the queue is actually running and able to read/write to redis. I personally use [this app](http://fastoredis.com/) to check what's going on in redis.

**Comment by ttacon** [comment]
Hi @MichalZak, any updates? Did @krazyjakee's example help? The issue here is as he pointed out, Arena is expecting a top level `queues` object.
