### ISSUE TITLE
job : Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by hungln213** [bee-queue/arena#51]
sometime error when click job. 

> 9/20/2017 4:07:05 PMArena is running on port 4567
> 9/20/2017 4:07:08 PM/opt/arena/node_modules/bull/lib/job.js:434
> 9/20/2017 4:07:08 PM  var job = new Job(queue, json.name || Job.DEFAULT_JOB_NAME, json.data, json.opts);
> 9/20/2017 4:07:08 PM                               ^
> 9/20/2017 4:07:08 PM
> 9/20/2017 4:07:08 PMTypeError: Cannot read property 'name' of undefined
> 9/20/2017 4:07:08 PM    at Function.Job.fromJSON (/opt/arena/node_modules/bull/lib/job.js:434:32)
> 9/20/2017 4:07:08 PM    at Redis.<anonymous> (/opt/arena/node_modules/bull/lib/queue.js:309:23)
> 9/20/2017 4:07:08 PM    at emitThree (events.js:135:13)
> 9/20/2017 4:07:08 PM    at Redis.emit (events.js:216:7)
> 9/20/2017 4:07:08 PM    at Redis.exports.returnReply (/opt/arena/node_modules/ioredis/lib/redis/parser.js:116:14)
> 9/20/2017 4:07:08 PM    at JavascriptRedisParser.returnReply (/opt/arena/node_modules/ioredis/lib/redis/parser.js:27:13)
> 9/20/2017 4:07:08 PM    at JavascriptRedisParser.execute (/opt/arena/node_modules/redis-parser/lib/parser.js:574:12)
> 9/20/2017 4:07:08 PM    at Socket.<anonymous> (/opt/arena/node_modules/ioredis/lib/redis/event_handler.js:107:22)
> 9/20/2017 4:07:08 PM    at emitOne (events.js:115:13)
> 9/20/2017 4:07:08 PM    at Socket.emit (events.js:210:7)
> 9/20/2017 4:07:08 PM    at addChunk (_stream_readable.js:252:12)
> 9/20/2017 4:07:08 PM    at readableAddChunk (_stream_readable.js:239:11)
> 9/20/2017 4:07:08 PM    at Socket.Readable.push (_stream_readable.js:197:10)
> 9/20/2017 4:07:08 PM    at TCP.onread (net.js:588:20)
> 9/20/2017 4:07:08 PM[nodemon] app crashed - waiting for file changes before starting...

**Comment by krazyjakee** [comment]
Is this still an issue? Do you have some steps to recreate it or is it truly random?

If so, I think we need some kind of retry/back off logic to give the client a more constructive message.

**Comment by hungln213** [comment]
Yes, this is an issue. 
My Steps:
List queue --> click view detail someone job (maybe a few times) --> crash app.

**Comment by Asp3ctus** [comment]
+1

**Comment by Asp3ctus** [comment]
It seems that it is fixed in
https://github.com/OptimalBits/bull/issues/673
i have run yarn upgrade bull and it seems that it have fixed the issue

**Comment by ttacon** [comment]
@hungln213 can you confirm if this fixes the issue for you? Thanks!

**Comment by devmetal** [comment]
@ttacon Hi, in this morning i faced with same issue. After i ran the upgrade the error is gone :) I think its fixed.

**Comment by mathieupythian** [comment]
Fixed in PR: https://github.com/bee-queue/arena/pull/78

**Comment by mathieupythian** [comment]
Fixed in 2.3.0

**Comment by bradvogel** [comment]
Thanks!
