### ISSUE TITLE
Add filter by status

### ISSUE THREAD

**Issue by PauloFerreira25** [bee-queue/arena#52]
Hello,
Please add a way to know by message status, which queue has message.
For example, have a location that shows which queues with failed messages. Or what are the queues that have messages in wait.
I have about 200 rows, and it's pretty bad having to open one by one to know the states.
Thanks for listening.

**Comment by krazyjakee** [comment]
So show the details of the queue right in the overview so you don't have to click through each one? I think it's a great idea, however, it's costly to query redis as heavily as this.

I think it could be achieved with some front-end magic by lazily retrieving the queue details one by one, perhaps even with some lazy live updating too.

**Comment by PauloFerreira25** [comment]
No need to show the details, just something like:
Queues with errors: 
| queue | number |
|ABC    | 10          |
| XYS   | 5            |
When choosing the queue, go to specific part of the queue.
I understand that if the queue has many messages this will create a problem.
So that my queues cleaning is super fast.
but it would help a lot if that was already done in the arena.
thanks for listening.

**Comment by afrozl** [comment]
I have the same request. We use a queue per task/job type so its hard to find failed jobs without opening each queue.

**Comment by scottbasgaard** [comment]
Bumping this as it would be a really nice feature.

I'm thinking either a filter like proposed here or some kind of icon / badge on Queues overview page with the status of all queues (job count), but for now just something there would be good.

**Comment by skeggse** [comment]
This sounds like #23. If there's a difference, please feel free to re-open.
