### ISSUE TITLE
Ability to add a job

### ISSUE THREAD

**Issue by krazyjakee** [bee-queue/arena#53]
This is super useful for debugging purposes. I can test the process functions on jobs by quickly adding them and varying the data.

- [x] Add a button in the Queue overview "Add Job"
- [x] On click open an empty [JSON editor](http://jsoneditoronline.org/) for the user to populate.
- [x] On submit, show a success notification but keep the data in the editor for further debugging.
- [x] Add a close button to clear and close the JSON editor.

**Comment by hraban** [comment]
Great feature, very happy to see it hit main.

Please could we also add a feature to just enter raw HTML? The current editor is very limiting: no copy paste, unintuitive icons without labels, unintuitive interface, many clicks to create simple jobs, etc...

No doubt it's useful in a streamlined workflow, but if you just want to add a quick job, this interface can be confusing and time consuming.

A little toggle to go from:

![current](https://user-images.githubusercontent.com/137852/56585168-34377580-65d5-11e9-8b61-4dd57aa56056.png)

to:

![desired](https://user-images.githubusercontent.com/137852/56585275-6ba62200-65d5-11e9-98f5-3386ea49172b.png)

would do wonders! :)

thanks

**Comment by sibelius** [comment]
any progress on this?

**Comment by rootux** [comment]
Yes please

**Comment by krazyjakee** [comment]
Very sorry to all but others are welcome to fork my fork, rebase from upstream and create a new PR.

Sorry to have kept it open so long.

**Comment by hraban** [comment]
issue copied to #203
