### ISSUE TITLE
Interface polish

### ISSUE THREAD

**Issue by krazyjakee** [bee-queue/arena#54]
- [x] Sort Queues in the overview alphabetically.
- [x] "Queue Navigation Tree" is basically breadcrumbs, let's take back that real-estate and have a horizontal breadcrumb at the top.
- [x] ~~Put some system statistics in the overview.~~ Ok nvm this
- [x] Make statistic numbers human readable (gb, mb etc). #42
- [ ] Localize times #27

Other than that, I love the simplicity of this queue manager.

**Comment by skeggse** [comment]
This is tracked in other tickets (i.e. #27), closing.
