### ISSUE TITLE
expressjs use Helmet

### ISSUE THREAD

**Issue by PauloFerreira25** [bee-queue/arena#57]
Please add use Helmet in express

http://expressjs.com/pt-br/advanced/best-practice-security.html

**Comment by krazyjakee** [comment]
For those who want details in english: http://expressjs.com/en/advanced/best-practice-security.html#use-helmet

**Comment by skeggse** [comment]
This seems out of scope for this project. I recommend you configure the express application yourself and attach helmet to it prior to attaching arena. Feel free to argue otherwise!
