### ISSUE TITLE
Live updates

### ISSUE THREAD

**Issue by krazyjakee** [bee-queue/arena#61]
Please forgive my lack of redis knowledge, but do any events in this library allow for redis to trigger an update in the server and therefore client? https://github.com/NodeRedis/node_redis - We're getting into websocket or long-poll territory then and perhaps that's going overboard.

If not, I guess a front-end interval would suffice. Since this would be ajaxy as hell, I suggest we perhaps solve this issue first: https://github.com/bee-queue/arena/issues/58

I'd like to see a job go from state to state without clicking a thing.

**Comment by skeggse** [comment]
I think we're getting into websocket/long-poll territory. While this would be super neat, I think the actual functionality should be out of scope for arena. I think it would, however, be reasonable to make arena extensible such that a separate plugin could add realtime updates, though that may be venturing into a separate space where the UI is client-rendered, per #58.
