### ISSUE TITLE
Implement move a task to another queue

### ISSUE THREAD

**Issue by PauloFerreira25** [bee-queue/arena#66]
Please implement the function of moving a job from one queue to another queue.

I ask this, then, I sent 90 messages to one queue and should have sent them to another. Typing error. So I had no way to move, I had to redo everything, a little work.

Thanks for listening

**Comment by skeggse** [comment]
I think this is probably out of scope for arena. The underlying queue technologies would need to support this, and bee-queue doesn't. Maybe bull does? Doing this kind of operation safely (i.e. exactly-once semantics, avoiding duplicate processing etc) is tricky in the best of circumstances.
