### ISSUE TITLE
Need to pass skipVersionCheck redis option to bull.

### ISSUE THREAD

**Issue by joe-at-startupmedia** [bee-queue/arena#67]
Currently there seems to be no ability to pass this flag in the redis options.

**Comment by joe-at-startupmedia** [comment]
Here is a list of all of the possible option for ioredis:

```
  port: 6379,
  host: 'localhost',
  family: 4,
  connectTimeout: 10000,
  retryStrategy: function (times) {
    return Math.min(times * 50, 2000);
  },
  keepAlive: 0,
  noDelay: true,
  connectionName: null,
  // Sentinel
  sentinels: null,
  name: null,
  role: 'master',
  sentinelRetryStrategy: function (times) {
    return Math.min(times * 10, 1000);
  },
  // Status
  password: null,
  db: 0,
  // Others
  dropBufferSupport: false,
  enableOfflineQueue: true,
  enableReadyCheck: true,
  autoResubscribe: true,
  autoResendUnfulfilledCommands: true,
  lazyConnect: false,
  keyPrefix: '',
  reconnectOnError: null,
  readOnly: false,
  stringNumbers: false
```

Currently this is abstracted to use Bee or Queue, and I am not sure if Bee is also using ioredis or if either will change redis clients in the future. For that reason I would advise on some way to provide arbitrary options for the following:
- options to be passed to bull or queue
- options to be passed to the redis client used by bull or queue

**Comment by skeggse** [comment]
bee-queue currently uses node_redis, but has [an open PR](https://github.com/bee-queue/bee-queue/pull/21) to switch to ioredis. We're mostly waiting to see how ioredis and node_redis settle as they indicated an [intent to merge](https://github.com/NodeRedis/node_redis#consolidation-its-time-for-celebration) part or all of their projects.

**Comment by joe-at-startupmedia** [comment]
That interesting. Regardless of when this eventually takes place, changes can be made to allow providing arbitrary options regardless of which client is used because fortunately both queue managers accept and `options` parameter and an `options.redis`. It's just that options is currently built for specific values. Could this be revised to allow options to be dynamically mapped?

```
    const options = {
      prefix,
      redis: url || { port, host, db, password }
    };

    let queue;
    if (isBee) {
      Object.assign(options, {
        isWorker: false,
        getEvents: false,
        sendEvents: false,
        storeJobs: false
      });
      queue = new Bee(name, options);
    } else {
      queue = new Bull(name, options);
    }
```

**Comment by vhf** [comment]
I'd also need this to be able to use Sentinel / custom ioredis client, would you accept a PR changing this?

More specifically, we need to be able to pass [`RedisOpts`](https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queue) to bull-arena.

**Comment by bradvogel** [comment]
Yes, saw the PR, thanks!
