### ISSUE TITLE
Job name not displayed

### ISSUE THREAD

**Issue by sylvainlap** [bee-queue/arena#69]
Hi,

In Arena, when viewing a job, its name is not displayed.
Is that possible to add this info to the Job details page ?

Regards,
Sylvain

**Comment by ttacon** [comment]
Can you upload a screenshot exemplifying what you mean? Thanks!

**Comment by sylvainlap** [comment]
Each job can have a name: https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queueadd, thanks to this signature: `queue.add(name: string, data: any).

Here is my code:
![capture](https://user-images.githubusercontent.com/8457604/33167000-70acce3c-d03c-11e7-8a95-8604fa3d1125.PNG)

You can see that my `cronQueue` has 3 process functions. However, in Arena, this `job.name` is not displayed:
![capture2](https://user-images.githubusercontent.com/8457604/33167165-e77e1250-d03c-11e7-8ecc-383e12dc7ad8.PNG)

However, you can easily get it, as it is written in the JSON:
![capture3](https://user-images.githubusercontent.com/8457604/33167183-f93a0170-d03c-11e7-84ff-0727b1191872.PNG)

**Comment by sylvainlap** [comment]
I suppose all happens in this file: https://github.com/bee-queue/arena/blob/master/src/server/views/partials/dashboard/jobDetails.hbs

You can add `this.name` somewhere. I could submit a PR, but I'm a backend dev, and I really suck at html :(

**Comment by skeggse** [comment]
Fixed in 81c11fa, released in v2.2.2.
