### ISSUE TITLE
Retry jobs only processing # of processes

### ISSUE THREAD

**Issue by lightninglu10** [bee-queue/arena#73]
Hey guys, when we use bull-arena and try to retry failed jobs, we only process through the total # of running workers of bull.

So for example in our queue we instantiate the number of processes like this: 

`logHandlerQueue.process(5, path.resolve(__dirname, 'handlers.js'))`

And then when we retry jobs, only 5 runs at once, each time. The rest just go directly back into the fail queue and not wait. Is this intended?

**Comment by lightninglu10** [comment]
I just tried this setting the number of processes to 100, and now they all try at once and have 80+ active.

I was expecting these processes to remain in the wait queue until they were picked up, but that didn't happen and they just immediately appeared back into the fail queue except the 5 that were active.

**Comment by skeggse** [comment]
This probably isn't a concern for you any longer. If it is, feel free to re-open; a [reprex](https://stackoverflow.com/help/minimal-reproducible-example) would go a long way to resolving this!
