### ISSUE TITLE
adding host adress

### ISSUE THREAD

**Issue by bol83** [bee-queue/arena#89]
in the index.js
we want to add the hostadress "127.0.0.1 "to the app.listen.
Thats not possible now? or am i missing something

Can the index.js file be something like the one below:

const port = listenOpts.port || 4567
// START NEW FEATURE --> 
// #############################################
// add this option const 
const host= listenOpts.host || '0.0.0.0';
// #############################################
// <-- END NEW FEATURE 
  if (!listenOpts.disableListen) {
    app.listen(port, host, () => console.log(`Arena is running on port ${port} at host ${host}`));
  }

**Comment by dotob** [comment]
would it help if a made a pr for this?

**Comment by ttacon** [comment]
Yup! PRs are always welcome!

**Comment by ttacon** [comment]
#114 has now been merged - we'll cut a new release a push up a new docker image soon.
