### ISSUE TITLE
Replace dependencies on CDN with local ones

### ISSUE THREAD

**Issue by marcbachmann** [bee-queue/arena#90]
I'm working on a project where we there's no decent internet connection setup.
This basically renders the dashboard useless.
What's your opinion regarding replacing the assets hosted on cdn.jsdelivr.net with local ones.
This will affect the jquery, bootstrap and highlightjs.

https://github.com/bee-queue/arena/blob/be866d368b44f95dbe4424ba71d6b5ec7d7843e9/src/server/views/layout.hbs#L9-L16

**Comment by ttacon** [comment]
I'd prefer we don't do a full swap out here (as we'd lose the benefit of the CDN for other users 😄 ). However, I wouldn't be strongly opposed to make the location a template variable that defaults the the CDN host but that could be overridden by a configuration value.

**Comment by marcbachmann** [comment]
https://github.com/bee-queue/arena/pull/91 👏
